Gemfile, Gemfile.lock, README.md, config/envato.yml
/cc @envato/discovery @johnsyweb
=> Spam us with open discovery PRs

config/envato.yml
Context
-------
[09:01] Jacob Bednarz: maybe `marketplace-puppet` pull requests belong in the #mp-site-reliability channel?
Cc
--
@jacobbednarz
=> marketplace-puppet → #mp-site-reliability

config/envato.yml
=> Marketplace debian package build scripts

config/envato.yml
The on-call developer often gets asked to audit items and email users with vulnerabilities. Let's make it easier for them by not having stale code.
Monitor Handdrill & ThemeAudit repositories for PRs!
@envato/marketplace
=> Let's not forget these useful tools!

config/envato.yml, lib/github_fetcher.rb, lib/seal.rb, spec/github_fetcher_spec.rb, spec/seal_spec.rb
Let's use the Github Team members list instead of typing out every member
=> GitHub team config option

config/envato.yml
Finance team is working on CQRS template for upcoming projects.
Let's add these repos to fine ants seal.
=> Add some more repos for finance team

config/envato.yml
**Context:**
@jayvee recently said:
sorry @johnsyweb too busy creating my own PR :wink: we need the seal!
**Change:**
Do what he say!
=> Even leads need the occasional nudge

config/envato.yml
Adds config for the Infrastructure team.
Is there any way to test this config now?
/cc @johnsyweb
=> Add infrastructure team

config/envato.yml
We've found other ways to bring attention to our PRs so removing the seal as it looks like everyone in our team is ignoring it
=> Remove finance seal

config/envato.yml
There is no need to have seal go on about the same pull request in
multiple channels. Let's leave the alerts to the single most correct
channel.
=> Stop the duplication

config/envato.yml
Context
-------
Seal has been choking since this repository was removed on 31 August.
Change
------
Remove the repo
Cc
--
@envato/customer-uptime
=> Remove marketplace-ansible from Seal

config/envato.yml
Context
--------
Following a conversation with @jayvee this morning and [my strong, weakly-held opinion](https://envato.slack.com/archives/marketplacedev/p1470292242001247) that we should archive [#marketplacedev](https://envato.slack.com/archives/marketplacedev).
Change
--------
- Move Seal outputs to where they belong
Complementary and complimentary image
--------------------------------------------
Conversation
---------------
Discuss, in https://envato.slack.com/archives/customer-engineering/p1475800984000032
=> Help me Melvin Conway -- You're my only hope!

config/envato.yml
One of my reasons for pointing the Seal to #customer-engineering in #31 was to increase the visibility of PRs across the Cutomer Engineering group. It occurred to me that I'd not seen anything of the great work that's going on in Foundation.
Let's increase the visibility of the work that's happening in Foundation.
Are there any missing repositories? Is now the time to add in the @envato/discovery stacks?
=> Shopfront projects are a customer concern

config/envato.yml
We renamed the channel a while back. Fixed!
=> Update sealbot channel

config/envato.yml
Since the process is more closely managed now and it's getting a bit irritating for everyone :)
=> Removes notifications for new-coding-test

config/envato.yml
Context: https://envato.slack.com/archives/C1Y455CTG/p1492560958915041
=> Redirect the Seal

config/envato.yml
Adding config for the Identity team.
=> Add Identity team

config/envato.yml
Add config for FinanceDev team
=> Add finance-dev team

config/envato.yml
Seal is too noisy for us and not enough folks use it
🔪 🐳
=> Remove Identity Team

config/envato.yml
More projects, more repos to monitor PRs for...
=> More repos for financedev

config/envato.yml
Add q-branch repos to configuration
=> Add q-branch repos to configuration

config/envato.yml
The repo no longer exists in github causing the seal app to fail
=> Remove referenced repos that no longer exist

config/envato.yml
Add config for FinanceDev [money-out] team
=> Money out config

config/envato.yml
Time to get rid of this since Boxen has been sunset.
=> Remove Boxen notifications

config/envato.yml
Adds a new repo to q-branch
Also removes some dead channels
=> Remove infrastructure config

config/envato.yml, lib/github_fetcher.rb
Seal has been bailing out on us.
- Add some logging.
- Correct team name
- Should add Rollbar reporting
@patrobinson, @mjward
=> Meaningful errors

config/envato.yml
Acquaint the little fella to Platform Communicator.
=> Add platform communicator to repos for money-out

config/envato.yml
=> Add platform communicator to money out

config/envato.yml
Remove a couple of legacy repos, add a few news ones
=> Update money out repo watch list

config/envato.yml
=> Add tax summaries coordinator to list of money out repos

config/envato.yml
Our team renamed and has some different systems under our purview, now.
=> Content curation => Complex content rename and reassignment

config/envato.yml, lib/github_fetcher.rb
=> Dont fail on missing repos
